# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[❯](bold blue)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


[username]
style_user = "blue bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true


[hostname]
ssh_only = false
format =  "at [$hostname](bold blue) in "
trim_at = ".companyname.com"
disabled = false